### ISSUE TITLE
JCenter sunset is announced; please republish library version(s) to Maven Central 

### ISSUE THREAD

**Issue by dejan2609** [Gericop/ColorPicker#6]
**_Rationale_**: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Quote (from a link above):
> **_May 1st | Bintray, JCenter, GoCenter, and ChartCenter services will no longer be available_**

**_Note:_** it seems that Signal Android app depends on this (among many other projects).

@Gericop let me know if I can help you with this.

**Comment by gregkorossy** [comment]
Yeah, I'll have to migrate several projects to Maven Central. If you had a good article that could guide me through the steps, I'd appreciate it.

**Comment by dejan2609** [comment]
Here you go @Gericop: https://blog.autsoft.hu/publishing-an-android-library-to-mavencentral-in-2019 
And guess what: @zsmb13 (who wrote this blog post) is also from Budapest 😃

**Comment by zsmb13** [comment]
Thanks for the mention, let me redirect you to my updated guide: https://getstream.io/blog/publishing-libraries-to-mavencentral-2021/

**Comment by gregkorossy** [comment]
@dejan2609 Started preparing stuff for it. However, I see that the Signal app uses a very old version of the lib (0.9.1, released on 17 September 2017) which was based on the support lib. The _new_ versions are based on AndroidX. Will Signal update the version to use the new lib instead of the old? It has a different group ID as well (old: `com.takisoft.fix`, new: `com.takisoft.colorpicker`).

**Comment by dejan2609** [comment]
@Gericop makes sense... let me investigate this.

**Comment by gregkorossy** [comment]
I'm not 100% sure but I think there were no breaking changes other than the backing API being based on the AndroidX classes instead of the support ones.

**Comment by dejan2609** [comment]
@Gericop Luckily, Signal-Android is also based on AndroidX 😃 
So, I think managed to perform a colorpicker upgrade to a version 1.0.0.

Feel free to check that specific commit (I am especially interested about your opinion related to a colorpicker module exclusions (that I got deleted).

**Comment by gregkorossy** [comment]
Seems ok to me. I guess the modules were excluded because they were used by the old support lib and the jetifier already replaced those in the build process, but since the new versions use AndroidX they don't need to be excluded.
Just a heads up: there has been an [issue](https://github.com/google/flexbox-layout/issues/263) with the flexbox layout that is used for laying out the color items in the dialog that results in the colors being loaded later than they should be. This is just a minor (cosmetic) issue and probably affects only users who use the app in landscape mode on smaller screens anyways.

**Comment by dejan2609** [comment]
@Gericop  JFrog partially reversed their decision, so you don't need to rush:

![image](https://user-images.githubusercontent.com/19467899/107848983-5b89b300-6df8-11eb-8012-4cc025917d36.png)

**Comment by gregkorossy** [comment]
Well, the day finally came. The color picker lib has been released to the maven central (1.0.0 with the original and 1.0.1 with slightly updated dependencies). 🥳
[https://search.maven.org/artifact/com.takisoft.colorpicker/colorpicker/](https://search.maven.org/artifact/com.takisoft.colorpicker/colorpicker/)

Better late than never, right? 😅
